### PR TITLE
Fix duoT5 prompt

### PR DESCRIPTION
**Pull request by janheinrichmerker**
Changed prompt as per:
https://github.com/castorini/pygaggle/blob/master/pygaggle/data/create_msmarco_duot5_input.py#L6

### CODE REVIEW

**Comment by seanmacavaney** [comment]
Nice catch, @heinrichreimer! Clearly this changes the outputs (as also identified by the tests). Did you happen to take some before/after benchmarks on this?

Thanks!

**Comment by janheinrichmerker** [comment]
Unfortunately not. I just noticed the difference while customizing the duoT5 approach for another paper.

**Comment by janheinrichmerker** [comment]
Should be fixed now.

**Comment by seanmacavaney** [comment]
Any chance we could see before/after performance on some dataset (e.g., a TREC DL19?)

**Comment by janheinrichmerker** [comment]
I'll try if I can set up some experiment.

**Comment by cmacdonald** [comment]
@heinrichreimer any update on this?

**Comment by janheinrichmerker** [comment]
Unfortunately, while I was setting up a little benchmark, I ran into another problem which seems to be related to the truncation.
The prompts often exceed 512 tokens and that ultimately overflows my GPU memory.

**Comment by seanmacavaney** [comment]
Thanks for the update! A few things you can try here:
 - Reducing the `batch_size` (default is 4)
 - Disabling CUDA to run on CPU instead (e.g., by setting `CUDA_VISIBLE_DEVICES=-1`)

hth

**Comment by janheinrichmerker** [comment]
Here we go for [`msmarco-passage/trec-dl-2019/judged`](https://ir-datasets.com/msmarco-passage.html#msmarco-passage/trec-dl-2019/judged):

| name | ndcg_cut_10 | recip_rank | map |
|---|:-:|:-:|:-:|
| BM25 | 0.479540 | 0.795028 | 0.370004 |
| BM25+duoT5 (corrected prompt) | 0.642777 | 0.933140 | 0.177057 |
| BM25+duoT5 (uncorrected prompt) | 0.600982 | 0.889535 | 0.173231 |

Nothing too fancy, but at least shows that, as expected, the effectiveness improves with the corrected prompt.

Code to reproduce:
```python
msmarco = get_dataset('msmarco_passage')
trec_dl = get_dataset('irds:msmarco-passage/trec-dl-2019/judged')
bm25 = BatchRetrieve(msmarco.get_index('terrier_stemmed_text'), wmodel='BM25')
pipeline1 = bm25 % 20 >> get_text(trec_dl, "text") >> DuoT5ReRankerFixed(batch_size=1)
pipeline2 = bm25 % 20 >> get_text(trec_dl, "text") >> DuoT5ReRanker(batch_size=1)
result = Experiment(
    [bm25, pipeline1, pipeline2],
    topics=trec_dl.get_topics(),
    qrels=trec_dl.get_qrels(),
    eval_metrics=["ndcg_cut_10", "recip_rank", "map"],
    names=["BM25", "BM25+duoT5 (corrected prompt)", "BM25+duoT5 (uncorrected prompt)"]
)
print(result.to_string(min_rows=len(result)))
```

**Comment by seanmacavaney** [comment]
Grand, thanks! Looks good to me.

**Pull request merged**
